# -*- coding: utf-8 -*-
"""RegresionStudentPerformance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xt9G2YsDdohSUWOuJ_9N29cCv8P1FxQP
"""

#pip install kagglehub[pandas-datasets]

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib
#Linea para solucionar bug en mac
matplotlib.use('TkAgg')  # o 'Qt5Agg'
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
from sklearn.preprocessing import StandardScaler

# %matplotlib inline

import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
# The error was caused by an empty string for file_path.
# This should be a specific file within the dataset, e.g., 'student_performance_dataset.csv'.
file_path = "student_performance_dataset.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "harshadapatil31/student-performance-and-study-habits-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

copy_df = df.copy()
copy_df.drop(columns=['student_id'], inplace=True)
print("-------- estadística descriptiva --------")
print(copy_df.describe())
print("-------- valores nulos --------")
print(copy_df.isnull().sum())
print("-------- info del dataset --------")
print(copy_df.info())

#['study_time_hours', 'attendance_percent', 'sleep_hours', 'part_time_job', 'previous_grade', 'internet_access', 'extracurricular_activities']
# 1. creacion de la copia del dataset original y su limpieza
data = copy_df[['study_time_hours', 'attendance_percent', 'sleep_hours', 'part_time_job', 'previous_grade', 'internet_access', 'extracurricular_activities']]
data['final_exam_score'] = copy_df['final_exam_score']
data[['internet_access', 'part_time_job', 'extracurricular_activities']] = data[['internet_access', 'part_time_job', 'extracurricular_activities']].replace({'Yes': 1, 'No': 0})
print(data.head())

print("-------- estadística descriptiva --------")
print(data.describe())
print("-------- info del dataset --------")
print(data.info())
print("-------- valores nulos --------")
print(data.isnull().sum())

# 2. EXPLORACIÓN DE PATRONES
print("--- Correlaciones con Exam Score ---")
corr = data.corr()

# Plot the heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Matriz de Correlación de Retornos Logarítmicos Mensuales')
plt.show()

# Identificar las variables numéricas y binarias
numerical_features = ['study_time_hours', 'attendance_percent', 'sleep_hours', 'previous_grade']
binary_features = ['part_time_job', 'internet_access', 'extracurricular_activities']

# Determinar el número total de plots
# 4 numéricas + 3 binarias  = 7 plots
num_plots = len(numerical_features) + len(binary_features)
n_cols = 3 # Número de columnas para la cuadrícula de plots
n_rows = (num_plots + n_cols - 1) // n_cols # Calcular el número de filas necesario

fig, axes = plt.subplots(n_rows, n_cols, figsize=(n_cols * 5, n_rows * 4))
axes = axes.flatten() # Aplanar el array de axes para fácil iteración

plot_index = 0

# Plots para variables numéricas
for feature in numerical_features:
    sns.scatterplot(
        data=data,
        x=feature,
        y='final_exam_score',
        hue='final_exam_score',
        palette='viridis',
        ax=axes[plot_index]
    )
    axes[plot_index].set_title(f'Score vs {feature.replace("_", " ").title()}')
    axes[plot_index].set_xlabel(feature.replace("_", " ").title())
    axes[plot_index].set_ylabel('Final Exam Score')
    axes[plot_index].grid(True, linestyle='--', alpha=0.6)
    plot_index += 1

# Plots para variables binarias
for feature in binary_features:
    sns.scatterplot(
        data=data,
        x=feature,
        y='final_exam_score',
        hue='final_exam_score',
        palette='viridis',
        ax=axes[plot_index]
    )
    axes[plot_index].set_title(f'Score vs {feature.replace("_", " ").title()}')
    axes[plot_index].set_xlabel(f'{feature.replace("_", " ").title()} (0=No, 1=Sí)')
    axes[plot_index].set_ylabel('Final Exam Score')
    axes[plot_index].set_xticks([0, 1])
    axes[plot_index].set_xticklabels(['No', 'Sí'])
    axes[plot_index].grid(True, linestyle='--', alpha=0.6)
    plot_index += 1

# Ocultar los ejes de plots vacíos si los hay
while plot_index < len(axes):
    fig.delaxes(axes[plot_index])
    plot_index += 1

plt.tight_layout()
plt.show()

data.hist(figsize=(10, 10), bins=20)
plt.show()

data.drop(columns=['part_time_job','internet_access','extracurricular_activities'])

X = data.iloc[:, :-1]
y = data.iloc[:, -1]

train_size = 800
X_train = X.iloc[:train_size, :]
y_train = y.iloc[:train_size]
X_test = X.iloc[train_size:, :]
y_test = y.iloc[train_size:]

# Scaling the values to help the gradient descent
def scale(x):
  return (x - np.mean(x))/np.std(x)

# Scale the features to prevent numerical instability in gradient descent
X_train_scaled = X_train.apply(scale)
X_test_scaled = X_test.apply(scale)

#hypothesis function (linear function)
def hypothesis(theta, x ,b):
  return np.dot(x, theta) + b

## MSE
def cost(y_predict, y):
  return np.sum((y_predict - y)**2)/(2*len(y))

## R^2
def r2_score(y_predict, y):
    ss_res = np.sum((y - y_predict)**2)
    ss_tot = np.sum((y - np.mean(y))**2)
    return 1 - (ss_res/ss_tot)

#Gradient Descent
def optimization(X, y, theta, b, alpha, num_iters=None):
    m = len(y)
    y_pred = hypothesis(theta, X, b)
    error = (y_pred - y)
    d_theta = np.dot(X.T, error) / m
    d_b = np.sum(error) / m
    theta = theta - alpha * d_theta
    b = b - alpha * d_b
    return theta, b, y_pred

# Inicialización
theta = np.random.rand(X_train_scaled.shape[1]) # Initialize theta based on the number of features in scaled X_train
b = 0.0
alpha = 0.01

max_epochs = 5000
r2_target = 0.95

cost_history = []
r2_history = []
epochs = 0

while True:
    # Use scaled training data for optimization
    theta, b, y_pred = optimization(X_train_scaled, y_train, theta, b, alpha)

    current_cost = cost(y_pred, y_train)
    current_r2 = r2_score(y_pred, y_train)

    cost_history.append(current_cost)
    r2_history.append(current_r2)

    epochs += 1

    if current_r2 >= r2_target or epochs >= max_epochs:
        print(f"Entrenamiento terminado en la época {epochs}")
        print(f"Costo final: {current_cost}")
        print(f"R2 final: {current_r2}")
        break

# Gráfica de convergencia del costo
plt.figure(figsize=(8,5))
plt.plot(cost_history)
plt.xlabel("Épocas")
plt.ylabel("Costo (MSE)")
plt.title("Convergencia del Gradiente Descendente")
plt.grid(True)
plt.show()

"""
# Gráfica de evolución del R2
plt.figure(figsize=(8,5))
plt.plot(r2_history)
plt.xlabel("Épocas")
plt.ylabel("R2")
plt.title("Evolución del R2")
plt.grid(True)
plt.show()
"""

dt_model = DecisionTreeRegressor(random_state=42)

dt_model.fit(X_train_scaled, y_train)

y_train_pred_dt = dt_model.predict(X_train_scaled)

y_test_pred_dt = dt_model.predict(X_test_scaled)

mse_train_dt = mean_squared_error(y_train, y_train_pred_dt)
r2_train_dt = r2_score(y_train, y_train_pred_dt)

mse_test_dt = mean_squared_error(y_test, y_test_pred_dt)
r2_test_dt = r2_score(y_test, y_test_pred_dt)

print("--- Decision Tree Regressor Performance ---")
print(f"Training Mean Squared Error: {mse_train_dt:.2f}")
print(f"Training R2 Score: {r2_train_dt:.2f}")
print(f"Testing Mean Squared Error: {mse_test_dt:.2f}")
print(f"Testing R2 Score: {r2_test_dt:.2f}")

# Check for overfitting
if r2_train_dt > r2_test_dt and abs(r2_train_dt - r2_test_dt) > 0.1:
    print("\nObservamos un posible *overfitting*! El modelo funciona mucho mejor en los datos de entrenamiento que en los datos de prueba.")
elif r2_train_dt < r2_test_dt:
    print("\nEl rendimiento en el conjunto de prueba es incluso mejor que en el de entrenamiento, lo cual es inusual. Podría haber un problema con la división de datos o el muestreo.")
else:
    print("\nEl rendimiento del modelo en los conjuntos de entrenamiento y prueba es consistente. No se observa *overfitting* significativo.")

"""# CLasificacion

### Opción 1: Clasificación de Trabajo de Medio Tiempo
Intentaremos clasificar `part_time_job` usando variables numéricas.
"""
"""
X_classification = data.drop(columns=['part_time_job'])
y_classification = data['part_time_job']

X_train, X_test, y_train, y_test = train_test_split(
    X_classification, y_classification, test_size=0.2, random_state=42, stratify=y_classification
)

cols_to_scale = ['study_time_hours', 'attendance_percent', 'sleep_hours', 'previous_grade', 'final_exam_score']

scaler = StandardScaler()
X_train = X_train.copy()
X_test = X_test.copy()
X_train[cols_to_scale] = scaler.fit_transform(X_train[cols_to_scale])
X_test[cols_to_scale] = scaler.transform(X_test[cols_to_scale])

model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("-------- Classification Report --------")
print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
ConfusionMatrixDisplay(cm).plot(cmap='Blues')
plt.title('Matriz de Confusión')
plt.show()
"""
