# -*- coding: utf-8 -*-
"""RegresionStudentPerformance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xt9G2YsDdohSUWOuJ_9N29cCv8P1FxQP
"""
# Commented out IPython magic to ensure Python compatibility.
import matplotlib
# Linea para solucionar bug en mac
matplotlib.use('TkAgg')  # o 'Qt5Agg'
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import kagglehub
from kagglehub import KaggleDatasetAdapter
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import tree
# %matplotlib inline

"""# Carga de datos"""

# Set the path to the file you'd like to load
# The error was caused by an empty string for file_path.
# This should be a specific file within the dataset, e.g., 'student_performance_dataset.csv'.
file_path = "student_performance_dataset.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "harshadapatil31/student-performance-and-study-habits-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

"""# Limpieza rápida"""

copy_df = df.copy()
copy_df.drop(columns=['student_id'], inplace=True)
print("-------- estadística descriptiva --------")
print(copy_df.describe())
print("-------- valores nulos --------")
print(copy_df.isnull().sum())
print("-------- info del dataset --------")
print(copy_df.info())

"""# Comienza el análisis del dataset"""

#['study_time_hours', 'attendance_percent', 'sleep_hours', 'part_time_job', 'previous_grade', 'internet_access', 'extracurricular_activities']
# 1. creacion de la copia del dataset original y su limpieza
data = copy_df[['study_time_hours', 'attendance_percent', 'sleep_hours', 'part_time_job', 'previous_grade', 'internet_access', 'extracurricular_activities']]
data['final_exam_score'] = copy_df['final_exam_score']
data[['internet_access', 'part_time_job', 'extracurricular_activities']] = data[['internet_access', 'part_time_job', 'extracurricular_activities']].replace({'Yes': 1, 'No': 0})
print(data.head())

print("-------- estadística descriptiva --------")
print(data.describe())
print("-------- info del dataset --------")
print(data.info())
print("-------- valores nulos --------")
print(data.isnull().sum())

# 2. EXPLORACIÓN DE PATRONES
print("--- Correlaciones con Exam Score ---")
corr = data.corr()

# Plot the heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Matriz de Correlación')
plt.show()

# Identificar las variables numéricas y binarias
numerical_features = ['study_time_hours', 'attendance_percent', 'sleep_hours', 'previous_grade']
binary_features = ['part_time_job', 'internet_access', 'extracurricular_activities']

# Determinar el número total de plots
# 4 numéricas + 3 binarias  = 7 plots
num_plots = len(numerical_features) + len(binary_features)
n_cols = 3 # Número de columnas para la cuadrícula de plots
n_rows = (num_plots + n_cols - 1) // n_cols # Calcular el número de filas necesario

fig, axes = plt.subplots(n_rows, n_cols, figsize=(n_cols * 5, n_rows * 4))
axes = axes.flatten() # Aplanar el array de axes para fácil iteración

plot_index = 0

# Plots para variables numéricas
for feature in numerical_features:
    sns.scatterplot(
        data=data,
        x=feature,
        y='final_exam_score',
        hue='final_exam_score',
        palette='viridis',
        ax=axes[plot_index]
    )
    axes[plot_index].set_title(f'Score vs {feature.replace("_", " ").title()}')
    axes[plot_index].set_xlabel(feature.replace("_", " ").title())
    axes[plot_index].set_ylabel('Final Exam Score')
    axes[plot_index].grid(True, linestyle='--', alpha=0.6)
    plot_index += 1

# Plots para variables binarias
for feature in binary_features:
    sns.scatterplot(
        data=data,
        x=feature,
        y='final_exam_score',
        hue='final_exam_score',
        palette='viridis',
        ax=axes[plot_index]
    )
    axes[plot_index].set_title(f'Score vs {feature.replace("_", " ").title()}')
    axes[plot_index].set_xlabel(f'{feature.replace("_", " ").title()} (0=No, 1=Sí)')
    axes[plot_index].set_ylabel('Final Exam Score')
    axes[plot_index].set_xticks([0, 1])
    axes[plot_index].set_xticklabels(['No', 'Sí'])
    axes[plot_index].grid(True, linestyle='--', alpha=0.6)
    plot_index += 1

# Ocultar los ejes de plots vacíos si los hay
while plot_index < len(axes):
    fig.delaxes(axes[plot_index])
    plot_index += 1

plt.tight_layout()
plt.show()

data.hist(figsize=(10, 10), bins=20)
plt.show()

data.drop(columns=['part_time_job','internet_access','extracurricular_activities'])

"""# Modelo de predicción a Mano"""

data_shuffled = data.sample(frac=1, random_state=42).reset_index(drop=True)
X = data_shuffled.iloc[:, :-1]
y = data_shuffled.iloc[:, -1]

train_size = 600
val_size = 200
test_size = len(X) - train_size - val_size
X_train = X.iloc[:train_size, :]
y_train = y.iloc[:train_size]
X_val = X.iloc[train_size:train_size+val_size, :]
y_val = y.iloc[train_size:train_size+val_size]
X_test = X.iloc[train_size+val_size:, :]
y_test = y.iloc[train_size+val_size:]

# Scaling the values to help the gradient descent
def scale(x):
  return (x - np.mean(x))/np.std(x)

# Scale the features for all sets
X_train_scaled = X_train.apply(scale)
X_val_scaled = X_val.apply(scale)
X_test_scaled = X_test.apply(scale)

#hypothesis function (linear function)
def hypothesis(theta, x ,b):
  return np.dot(x, theta) + b

## MSE
def cost(y_predict, y):
  return np.sum((y_predict - y)**2)/(2*len(y))

## R^2
def r2_score(y_predict, y):
    ss_res = np.sum((y - y_predict)**2)
    ss_tot = np.sum((y - np.mean(y))**2)
    return 1 - (ss_res/ss_tot)

#Gradient Descent
def optimization(X, y, theta, b, alpha):
    m = len(y)
    y_pred = hypothesis(theta, X, b)
    error = (y_pred - y)
    d_theta = np.dot(X.T, error) / m
    d_b = np.sum(error) / m
    theta = theta - alpha * d_theta
    b = b - alpha * d_b
    return theta, b, y_pred

# Inicialización
theta = np.random.rand(X_train_scaled.shape[1])
b = 0.0
alpha = 0.01
max_epochs = 5000
r2_target = 0.95

cost_history = []
r2_history = []
epochs = 0

while True:
    theta, b, y_pred = optimization(X_train_scaled, y_train, theta, b, alpha)
    current_cost = cost(y_pred, y_train)
    current_r2 = r2_score(y_pred, y_train)
    cost_history.append(current_cost)
    r2_history.append(current_r2)
    epochs += 1
    if current_r2 >= r2_target or epochs >= max_epochs:
        print(f"Entrenamiento terminado en la época {epochs}")
        print(f"Costo final: {current_cost}")
        print(f"R2 final: {current_r2}")
        break

# Crear una figura con dos subgráficas
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

# 1. Gráfica de convergencia del costo (MSE)
ax1.plot(cost_history, color='tab:red')
ax1.set_xlabel("Épocas")
ax1.set_ylabel("Costo (MSE)")
ax1.set_title("Convergencia del Gradiente Descendente (MSE)")
ax1.grid(True, linestyle='--', alpha=0.7)

# 2. Gráfica de evolución del R2
ax2.plot(r2_history, color='tab:blue')
ax2.set_xlabel("Épocas")
ax2.set_ylabel("R2 Score")
ax2.set_title("Evolución del R2 durante el entrenamiento")
ax2.grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

"""Evaluación con validación y prueba"""

y_val_pred = hypothesis(theta, X_val_scaled, b)
y_test_pred = hypothesis(theta, X_test_scaled, b)

mse_val = cost(y_val_pred, y_val)
r2_val = r2_score(y_val_pred, y_val)

mse_test = cost(y_test_pred, y_test)
r2_test = r2_score(y_test_pred, y_test)

print("--- Evaluación de Generalización ---")
print(f"VALIDACIÓN -> MSE: {mse_val:.4f}, R2: {r2_val:.4f}")
print(f"PRUEBA     -> MSE: {mse_test:.4f}, R2: {r2_test:.4f}")

metrics_df = pd.DataFrame({
    'Metric': ['MSE', 'R2'],
    'Train': [current_cost, current_r2],
    'Validation': [mse_val, r2_val],
    'Test': [mse_test, r2_test]
})
print(metrics_df)

"""# Modelo de predicción con Framework Versión 1"""

dt_model = DecisionTreeRegressor(max_depth=20, random_state=42)
dt_model.fit(X_train_scaled, y_train)

y_train_pred_dt = dt_model.predict(X_train_scaled)
y_val_pred_dt = dt_model.predict(X_val_scaled)
y_test_pred_dt = dt_model.predict(X_test_scaled)

# Cálculo de métricas
mse_train_dt = mean_squared_error(y_train, y_train_pred_dt)
r2_train_dt = r2_score(y_train, y_train_pred_dt)
mse_val_dt = mean_squared_error(y_val, y_val_pred_dt)
r2_val_dt = r2_score(y_val, y_val_pred_dt)
mse_test_dt = mean_squared_error(y_test, y_test_pred_dt)
r2_test_dt = r2_score(y_test, y_test_pred_dt)

print("--- Decision Tree Regressor Performance (Ajustado) ---")
print(f"Training   MSE: {mse_train_dt:.2f}, R2: {r2_train_dt:.4f}")
print(f"Validation MSE: {mse_val_dt:.2f}, R2: {r2_val_dt:.4f}")
print(f"Testing    MSE: {mse_test_dt:.2f}, R2: {r2_test_dt:.4f}")

if r2_train_dt > r2_test_dt and abs(r2_train_dt - r2_test_dt) > 0.1:
    print("\nObservamos un posible *overfitting*! El modelo funciona mucho mejor en los datos de entrenamiento que en los datos de prueba.")
elif r2_train_dt < r2_test_dt:
    print("\nEl rendimiento en el conjunto de prueba es incluso mejor que en el de entrenamiento, lo cual es inusual.")
else:
    print("\nEl rendimiento del modelo en los conjuntos de entrenamiento y prueba es consistente.")


"""# Modelo de predicción con Framework Versión 2"""

rf_model = RandomForestRegressor(n_estimators=500, 
                                 max_leaf_nodes=200, 
                                 n_jobs=-1, 
                                 random_state=42)

rf_model.fit(X_train_scaled, y_train)

y_train_pred_rf = rf_model.predict(X_train_scaled)
y_val_pred_rf = rf_model.predict(X_val_scaled)
y_test_pred_rf = rf_model.predict(X_test_scaled)

mse_train_rf = mean_squared_error(y_train, y_train_pred_rf)
r2_train_rf = r2_score(y_train, y_train_pred_rf)

mse_val_rf = mean_squared_error(y_val, y_val_pred_rf)
r2_val_rf = r2_score(y_val, y_val_pred_rf)

mse_test_rf = mean_squared_error(y_test, y_test_pred_rf)
r2_test_rf = r2_score(y_test, y_test_pred_rf)

print("--- Random Forest Regressor Performance ---")
print(f"Training   MSE: {mse_train_rf:.2f}, R2: {r2_train_rf:.4f}")
print(f"Validation MSE: {mse_val_rf:.2f}, R2: {r2_val_rf:.4f}")
print(f"Testing    MSE: {mse_test_rf:.2f}, R2: {r2_test_rf:.4f}")

if r2_train_rf > r2_test_rf and abs(r2_train_rf - r2_test_rf) > 0.1:
    print("\nObservamos un posible *overfitting*! El modelo funciona mucho mejor en los datos de entrenamiento que en los datos de prueba.")
elif r2_train_rf < r2_test_rf:
    print("\nEl rendimiento en el conjunto de prueba es incluso mejor que en el de entrenamiento, lo cual es inusual.")
else:
    print("\nEl rendimiento del modelo en los conjuntos de entrenamiento y prueba es consistente.")